name: Release to crates.io

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-cratesio:
    name: Publish crates to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Publish core
        run: cargo publish -p aimcal-core --no-verify --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: sleep 60
      - name: Publish cli
        run: cargo publish -p aimcal-cli --no-verify --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - run: sleep 60
      - name: Publish aimcal
        run: cargo publish -p aimcal --no-verify --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
